name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.WF_DB_PSW }}
          MYSQL_DATABASE: dev
          MYSQL_USER: testUser
          MYSQL_PASSWORD: ${{ secrets.WF_DB_PSW }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.BACHELOR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BACHELOR_DOCKERHUB_ACCESSTOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
        env:
          DB_USERNAME: testUser
          DB_PASSWORD: ${{ secrets.WF_DB_PSW }}
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: dev


      - name: Set unique image tag
        id: unique-image-tag
        run: echo "IMAGE_TAG=prod-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: danielneset/bachelor-websocket:${{ env.IMAGE_TAG }}
